### ISSUE TITLE
Where is dkms.conf?

### ISSUE THREAD

**Issue by shadow7412** [mohalisad/CentOS-RHEL-8-alx-driver#1]
I'm running through the setup script (though I'm unable to run it directly as I'm using manjaro rather than redhat) and on line 48 it seems to expect dkms.conf to exist in the current path.

I don't see any places in the script where the working directory is set, and there is no dkms.conf in the repository. So where is this file supposed to come from?

Thanks for your help.

**Comment by mohalisad** [comment]
Hey @shadow7412

As I mentioned in readme this is a fix based on [this repository](https://github.com/AMV007/alx_dkms_installer). I only changed a few line for red hat kernel to work. Please refer to the original repository to see the file.
